# Generated by Django 4.2.4 on 2023-12-31 17:29

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppPersonnel', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=155)),
                ('postnom', models.CharField(max_length=155)),
                ('prenom', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=155, unique=True)),
                ('matricule', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('sexe', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_engagement', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('salaire', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3)),
                ('prime', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3)),
                ('etat_civil', models.CharField(choices=[('M', 'M'), ('C', 'C'), ('V', 'V')], default='C', max_length=1)),
                ('demandeur', models.BooleanField(default=False)),
                ('approbateur', models.BooleanField(default=False)),
                ('consulteur', models.BooleanField(default=False)),
                ('sbgr', models.BooleanField(default=False)),
                ('planificateur', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('fonction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppPersonnel.fonction')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppPersonnel.grade')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
