# Generated by Django 4.2.4 on 2023-09-02 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppPersonnel', '0001_initial'),
        ('AppAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='fonction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppPersonnel.fonction'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppPersonnel.grade'),
        ),
    ]
