# Generated by Django 4.2.4 on 2023-09-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0002_alter_personnel_fonction_alter_personnel_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='sbgr',
            field=models.BooleanField(default=False),
        ),
    ]
