# Generated by Django 4.2.4 on 2023-09-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0003_personnel_sbgr'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='prime',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='salaire',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
    ]
