# Generated by Django 4.2.4 on 2023-10-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0004_personnel_prime_alter_personnel_salaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='etat_civil',
            field=models.CharField(choices=[('M', 'M'), ('C', 'C'), ('V', 'V')], default='C', max_length=1),
        ),
    ]
