# Generated by Django 4.2.4 on 2023-10-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0005_alter_personnel_etat_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='planificateur',
            field=models.BooleanField(default=False),
        ),
    ]
