# Generated by Django 4.2.4 on 2023-09-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPlanning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annee',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='annee',
            name='date_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='planning',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='planning',
            name='date_fin',
            field=models.DateField(),
        ),
    ]
