# Generated by Django 4.2.4 on 2023-09-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPlanning', '0002_alter_annee_date_debut_alter_annee_date_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='conge',
        ),
        migrations.AddField(
            model_name='planning',
            name='nature',
            field=models.CharField(choices=[('Cumulé', 'Cumulé'), ('Circonstance', 'Circonstance'), ('Annuel', 'Annuel'), ('Maternité', 'Maternité'), ('A valoir', 'A valoir')], default='', max_length=155),
            preserve_default=False,
        ),
    ]
