# Generated by Django 4.2.4 on 2023-09-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPlanning', '0003_remove_planning_conge_planning_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='nature',
            field=models.CharField(choices=[('Cumulé', 'Cumulé'), ('Annuel', 'Annuel'), ('A valoir', 'A valoir')], max_length=155),
        ),
    ]
