# Generated by Django 4.2.4 on 2023-09-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPlanning', '0004_alter_planning_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='nature',
            field=models.CharField(choices=[('Annuel', 'Annuel')], max_length=155),
        ),
    ]
