# Generated by Django 4.2.4 on 2023-09-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPlanning', '0005_alter_planning_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annee',
            name='designation',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
