# Generated by Django 4.2.4 on 2023-10-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPlanning', '0007_alter_planning_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='nature',
        ),
    ]
