# Generated by Django 4.2.4 on 2023-09-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='nature',
            field=models.CharField(choices=[('Circonstance', 'Circonstance'), ('Maternité', 'Maternité')], max_length=155),
        ),
    ]
