# Generated by Django 4.2.4 on 2023-09-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConge', '0002_alter_conge_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='nature',
            field=models.CharField(choices=[('Circonstance', 'Circonstance'), ('Maternité', 'Maternité'), ('Cumulé', 'Cumulé'), ('A valoir', 'A valoir')], max_length=155),
        ),
    ]
