# Generated by Django 4.2.4 on 2023-09-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppConge', '0003_alter_conge_nature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='personnel',
        ),
    ]
