# Generated by Django 4.2.4 on 2023-09-22 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppConge', '0004_remove_demande_personnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='conge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppConge.conge'),
        ),
    ]
