# Generated by Django 4.2.4 on 2023-09-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppConge', '0005_alter_demande_conge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='conge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppConge.conge'),
        ),
    ]
